// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwujRSRxXmB5W7hWxatHSiOxKKTNJURJ8',
    appId: '1:1045905756018:web:28c67a86b04b70c8a417eb',
    messagingSenderId: '1045905756018',
    projectId: 'flutter-crud-10655',
    authDomain: 'flutter-crud-10655.firebaseapp.com',
    storageBucket: 'flutter-crud-10655.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjHj4Y4mVz-u_GygwR2YmjNQDyFN4Jrhw',
    appId: '1:1045905756018:android:5ede7e6d872ddd42a417eb',
    messagingSenderId: '1045905756018',
    projectId: 'flutter-crud-10655',
    storageBucket: 'flutter-crud-10655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfQXojWakVd7SCyI-j4ougZfe_6W_xOc',
    appId: '1:1045905756018:ios:9ed6353639013379a417eb',
    messagingSenderId: '1045905756018',
    projectId: 'flutter-crud-10655',
    storageBucket: 'flutter-crud-10655.appspot.com',
    iosClientId: '1045905756018-62edr5b7sm5b1lis8sqsclt2n29lhsv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwfQXojWakVd7SCyI-j4ougZfe_6W_xOc',
    appId: '1:1045905756018:ios:34ad1700e75203c2a417eb',
    messagingSenderId: '1045905756018',
    projectId: 'flutter-crud-10655',
    storageBucket: 'flutter-crud-10655.appspot.com',
    iosClientId: '1045905756018-60nk809o5cqqde916hsjuld9scv8423f.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
